In [1]:
import numpy as np

# .creating a 1D numpy array


In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
print(a, b)
print(type(a))
print(type(b))

[1 2 3 4 5] [4 5 6 7 8]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
print(a + b)
print(a- b)
print(a * b)

[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]


# . Creating 2D matrix
matrix syntax- np.array([[], [], []]) -> 3 row matrix

->np.array([[1,2], [3,4], [5,6]])-> 3x2 matrix

In [8]:
n2 = np.array([[1,2], [2,3]])
print(n2)
print(n2.shape) #no of rows and columns
print(n2.ndim) #no of dimensions
print(n2.dtype) #data type of the elements

[[1 2]
 [2 3]]
(2, 2)
2
int32


In [9]:
#1 a matrix of number from 1 t 100  with gap of 5
np.arange(1, 100, 5) #start, ending, gap

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [11]:
#2 a matrix of numbers from 1 to 10 with 25 elements
np.linspace(1, 10, 25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [12]:
#3 a matrix of random numbers from 1 to 10 and shape 2x3
np.random.randint(1,10, size=(2,3))

array([[1, 4, 3],
       [7, 7, 1]])

In [14]:
# (optional) set numeric precision (decimal places)
np.set_printoptions(precision = 2)

In [15]:
#5 matrix of uniformally distributed random numbers  with shape 3x3
np.random.uniform(size=(3,3))

array([[0.74, 0.05, 0.24],
       [0.84, 0.28, 0.41],
       [0.32, 0.36, 0.31]])